##all: 				argument
##
##argument: 			argument.o
##					g++ argument.o -o argument
##
##argument.o : 		argument.c
##					g++ -c argument.c
##
##clean :				
##					rm -rf *o argument

all: 				argument

argument : 			argument.c
					g++ -c argument.c

clean :				
					rm -rf *o argument