all							: 	color_transform
				
color_transform				: 	color_transform.o 
				
color_transform.o 			:	color_transform.c
								g++ -c color_transform.c
				
clean 						:							
								rm -rf *o color_transform