all							: 	huffman_decoder
				
huffman_decoder				: 	huffman_decoder.o 
				
huffman_decoder.o 			:	huffman_decoder.c
								g++ -c huffman_decoder.c
				
clean 						:							
								rm -rf *o huffman_decoder